[package]
name = "game-of-life"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7"
embedded-hal = "1.0.0"
microbit-v2 = "0.15.1"
nanorand = { version = "0.7.0", default-features = false, features = ["pcg64"] }
panic-rtt-target = "0.2.0"
rtt-target = "0.6.1"

[dependencies.cortex-m]
features = ["inline-asm", "critical-section-single-core"]
version = "0.7.7"
